FROM python:3.12-slim-bookworm

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH="./src"

# Copy dependencies into the container
COPY pyproject.toml .
COPY uv.lock .
RUN uv sync --frozen --no-cache

# Copy the application into the container
COPY ./src .
COPY ./keys ./keys
COPY ../entrypoint.sh .

# Override entrypoint for tests
ENTRYPOINT ["uv", "run", "pytest", "-v"]
CMD ["src/tests", "-v"]