default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude_types: [svg, css, html, less, javascript, json, coffee, map, markdown, pem]
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: ./ugc_api/.venv/bin/isort
        language: python
        types: [python]
        args: []
        require_serial: false
        additional_dependencies: []

      - id: flake8
        name: flake8
        entry: ./ugc_api/.venv/bin/flake8
        language: python
        types: [python]
        args: [--config, ./ugc_api/setup.cfg]
        require_serial: false
        additional_dependencies: []

      - id: ruff
        name: ruff
        entry: ./ugc_api/.venv/bin/ruff
        language: python
        types: [python]
        args: [check]
        require_serial: false
        exclude: farfor
        additional_dependencies: []

      - id: mypy
        name: mypy
        entry: ./ugc_api/.venv/bin/mypy
        language: python
        types: [python]
        args: [--config-file, ugc_api/pyproject.toml]
        require_serial: false
        additional_dependencies: []
