POSTGRES_DSN = "postgresql://user:password@localhost:15432/test_db"
MONGO_URI = "mongodb://localhost:27017"
TEST_RANGE = 11000000
BATCH_SIZE = 10000
NUM_WORKERS = 12
OUTPUT_DIR = "data_batches"
INPUT_DIR = "data_batches"
NUM_THREADS = 10  # Количество параллельных потоков
NUM_WAVES = 5  # Количество волн тестирования
NUM_OPERATIONS_PER_WAVE = 10000  # Количество операций на волну
