name: UGC API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install "flake8>=7.1.1" "mypy>=1.14.1" "ruff>=0.9.3"

    - name: Lint with flake8
      run: |
        flake8 --config ./ugc_api/setup.cfg

    - name: Lint with ruff
      run: |
        ruff check --exclude research --output-format=github

    - name: Lint with mypy
      run: |
        mypy --config-file ugc_api/pyproject.toml --exclude research .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Prepare test environment
      run: |
        cp .env.example .env
        # Модифицируем некоторые переменные для тестового окружения
        sed -i 's/UGC_API_PRODUCTION=True/UGC_API_PRODUCTION=False/' .env
        sed -i 's/UGC_MONGO_DB=Movies/UGC_MONGO_DB=Movies_Test/' .env
        sed -i 's|SENTRY_DSN=.*|SENTRY_DSN=""|' .env

    - name: Run tests
      run: |
        make test

    - name: Send Telegram notification
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          ✅ Изменения успешно влиты в main!

          Repository: ${{ github.repository }}
          Branch: main

          Commit: ${{ github.sha }}
          ${{ github.event.commits[0].message }}

          Details: https://github.com/${{ github.repository }}/commit/${{github.sha}}
